# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  channel:
    image: mockoon/cli:9
    command: --data data --port 3000
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./ProvaTecnica.mockoon.json
        target: /data
  mysql:
    image: mysql:8.0
    container_name: poleepo_mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sa
      - MYSQL_DATABASE=poleepo
      - MYSQL_USER=prova
      - MYSQL_PASSWORD=prova
    volumes:
      - "mysql_data:/var/lib/mysql"
volumes:
  mysql_data:
  files:
